# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: npm install
  displayName: 'Install npm'

- script: npx playwright install
  displayName: 'Install Playwright'

- script: npm run test:azure
  displayName: 'Run all tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test-results/results.xml'
    mergeTestResults: true
    testRunTitle: 'Playwright JUnit Test Results'
  condition: always()
  displayName: 'Publish JUnit Test Results'
